import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Layout
        title={'Inicio'}
        description={'Emprendete Bazar es el sitio lider de compra y venta de productos de emprendedores locales en Tuxtla Gutíerrez, Chiapas.'}
      >
        <div className='contenedor'>
          <h1>Emprendete Bazar Inicio</h1>

        </div>
      </Layout>

      

      
    </>
  )
}
